In [16]:
import numpy as np

In [5]:
import math

In [7]:
(math.log(8, 2) + math.log(18, 2))/(2*math.log(2, 2) + math.log(3, 2))

2.0

In [9]:
math.log(20, 225)*math.log(15, 289)*math.log(17, 20)

0.25

In [10]:
from scipy import optimize

In [13]:
x = 1 
y = 1
def f(x,y):
    return x**3+4*(y**3)-3*x-3*y

In [27]:
print(np.eye(3,4,k=0)*2+np.eye(3,4,k=1))

array([[ 2.,  1.,  0.,  0.],
       [ 0.,  2.,  1.,  0.],
       [ 0.,  0.,  2.,  1.]])

In [39]:
import random
a = np.array(random.sample(range(1000), 24)) # одномерный массив из 12 случайных чисел от 1 до 1000
w = a.reshape((2,2,2,3)) # превратим w в трёхмерную матрицу
print(a)
print(w.reshape(1))


[237 777   9 787 202 972 360 677 717 726  27 500 156 657 381 210 224 711
 631 823 773 702 321 600]


ValueError: cannot reshape array of size 24 into shape (1,)

In [46]:
import numpy as np

x_shape = tuple(map(int, input().split()))
X = np.fromiter(map(int, input().split()), np.int).reshape(x_shape)
y_shape = tuple(map(int, input().split()))
Y = np.fromiter(map(int, input().split()), np.int).reshape(y_shape)
if x_shape[1] == y_shape[1]:
    print(X.dot(Y.T))
else:
    print('matrix shapes do not match')

2 3
8 7 7 14 4 6
4 3
5 5 1 5 2 6 3 3 9 1 4 6
[[ 82  96 108  78]
 [ 96 114 108  66]]


In [45]:
2 3
8 7 7 14 4 6
4 3
5 5 1 5 2 6 3 3 9 1 4 6

3 5


In [51]:
np.array([[1.5,3,4,6],
[2.5,2,7.5,4],
[3.5,1,3.5,2]]).mean(axis=0)

array([ 2.5,  2. ,  5. ,  4. ])

In [52]:
from urllib.request import urlopen
import numpy as np

filename = input()
f = urlopen(filename)
sbux = np.loadtxt(f,  delimiter=",", skiprows=10)
print(sbux.mean(axis=0))

https://stepic.org/media/attachments/lesson/16462/boston_houses.csv
[ 22.44768612   3.67767938  11.45774648   0.07042254   0.55584245
   6.28059155   3.76355674]


In [54]:
b1 = ((60+50+75)*((10+7+12)/3 - (10+7+12)))/((60+50+75)*((60+50+75)/3 - (60+50+75)))

In [56]:
x = np.array([[1,1,1], [60, 50, 75]])

In [58]:
x = x.T

In [59]:
x

array([[ 1, 60],
       [ 1, 50],
       [ 1, 75]])

In [62]:
y = np.array([[10],[7],[12]])

In [63]:
y

array([[10],
       [ 7],
       [12]])

In [66]:
step1 = x.T.dot(x)

In [67]:
step1

array([[    3,   185],
       [  185, 11725]])

In [69]:
step2 = np.linalg.inv(step1)

In [70]:
step2

array([[  1.23421053e+01,  -1.94736842e-01],
       [ -1.94736842e-01,   3.15789474e-03]])

In [71]:
step3 = step2.dot(x.T)

In [72]:
step3

array([[ 0.65789474,  2.60526316, -2.26315789],
       [-0.00526316, -0.03684211,  0.04210526]])

In [73]:

b = step3.dot(y)

In [75]:
b.round(3)

array([[-2.342],
       [ 0.195]])

In [76]:
import urllib
from urllib import request
import numpy as np

fname = 'https://stepic.org/media/attachments/lesson/16462/boston_houses.csv'
f = urllib.request.urlopen(fname)  # open file from URL
data = np.loadtxt(f, delimiter=',', skiprows=1)  # load data to work with
print(data)

[[  2.40000000e+01   6.32000000e-03   1.80000000e+01 ...,   5.38000000e-01
    6.57500000e+00   4.09000000e+00]
 [  2.16000000e+01   2.73100000e-02   0.00000000e+00 ...,   4.69000000e-01
    6.42100000e+00   4.96710000e+00]
 [  3.47000000e+01   2.72900000e-02   0.00000000e+00 ...,   4.69000000e-01
    7.18500000e+00   4.96710000e+00]
 ..., 
 [  2.39000000e+01   6.07600000e-02   0.00000000e+00 ...,   5.73000000e-01
    6.97600000e+00   2.16750000e+00]
 [  2.20000000e+01   1.09590000e-01   0.00000000e+00 ...,   5.73000000e-01
    6.79400000e+00   2.38890000e+00]
 [  1.19000000e+01   4.74100000e-02   0.00000000e+00 ...,   5.73000000e-01
    6.03000000e+00   2.50500000e+00]]


In [102]:
data.shape

(506, 7)

In [83]:
y=data[:,:1]

In [111]:
y.shape

(506, 1)

In [114]:
x.shape

(506, 6)

In [103]:
x = data[:,1:]

In [119]:
ones = np.ones_like(y)

In [120]:
X = np.hstack((ones, x))

In [121]:
X

array([[  1.00000000e+00,   6.32000000e-03,   1.80000000e+01, ...,
          5.38000000e-01,   6.57500000e+00,   4.09000000e+00],
       [  1.00000000e+00,   2.73100000e-02,   0.00000000e+00, ...,
          4.69000000e-01,   6.42100000e+00,   4.96710000e+00],
       [  1.00000000e+00,   2.72900000e-02,   0.00000000e+00, ...,
          4.69000000e-01,   7.18500000e+00,   4.96710000e+00],
       ..., 
       [  1.00000000e+00,   6.07600000e-02,   0.00000000e+00, ...,
          5.73000000e-01,   6.97600000e+00,   2.16750000e+00],
       [  1.00000000e+00,   1.09590000e-01,   0.00000000e+00, ...,
          5.73000000e-01,   6.79400000e+00,   2.38890000e+00],
       [  1.00000000e+00,   4.74100000e-02,   0.00000000e+00, ...,
          5.73000000e-01,   6.03000000e+00,   2.50500000e+00]])

In [123]:
step1 = X.T.dot(X)
step2 = np.linalg.inv(step1)
step3 = step2.dot(X.T)
b = step3.dot(y)

In [124]:
b

array([[ -3.65580429],
       [ -0.2163955 ],
       [  0.0737306 ],
       [  4.41245058],
       [-25.46844878],
       [  7.14320155],
       [ -1.30108768]])

In [132]:
import urllib
from urllib import request
import numpy as np

fname = 'https://stepic.org/media/attachments/lesson/16462/boston_houses.csv'
f = urllib.request.urlopen(fname)  # open file from URL
data = np.loadtxt(f, delimiter=',', skiprows=1)  # load data to work with
x,y =data[:,1:], data[:,:1]
X = np.hstack((np.ones_like(y), x))
b = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
print(*b)



AttributeError: 'numpy.ndarray' object has no attribute 'values'

In [179]:
for i in b:
    print(i, end=" ")

[-3.65580429] [-0.2163955] [ 0.0737306] [ 4.41245058] [-25.46844878] [ 7.14320155] [-1.30108768] 

In [143]:
[i for i in b]

[array([-3.65580429]),
 array([-0.2163955]),
 array([ 0.0737306]),
 array([ 4.41245058]),
 array([-25.46844878]),
 array([ 7.14320155]),
 array([-1.30108768])]