In [1]:
import numpy as np

In [128]:
w = np.array([[0,0,0]])

In [52]:
w

array([[ 1. ,  1.6, -3.1]])

In [31]:
w.shape

(1, 3)

In [33]:
examples = np.array([[1, 1, 0.3], [1,0.4,0.5], [1,0.7,0.8]])

In [32]:
examples[0]

array([ 1. ,  1. ,  0.3])

In [96]:
def Target(ex):
    if ex[1] == 1 and ex[2] == 0.3:
        return 1
    elif ex[1] == 0.4 and ex[2] == 0.5:
        return 1
    elif ex[1] == 0.7 and ex[2] == 0.8:
        return 0

In [103]:
def Prdict(example):
    sum = example[0]*w[0][0] + example[1]*w[0][1] + example[2]*w[0][2]
#     print('example' , example)
#     print('sum', sum)
    if sum > 0:
        return 1
    else:
        return 0

In [65]:
examples[2][0]*w[0][0] + examples[2][1]*w[0][1] + examples[2][2]*w[0][2]

-0.36000000000000032

In [59]:
examples[2]*w[0][2]

array([-3.1 , -2.17, -2.48])

In [129]:
perfect = False

In [130]:
count = 0
while not perfect:
    perfect = True
    
    for e in examples:
        count += 1
        print('шаг', count)
        print('e =', e)
        print('{} - Prdict(e) = = {} - Target(e)'.format(Prdict(e), Target(e)))
        if Prdict(e) != Target(e):
#             print('{} - Prdict(e) ! = {} - Target(e)'.format(Prdict(e), Target(e)))
            perfect = False
            if Prdict(e) == 0:
                print('прибавляем к', w, ',e', e, 'Predict == 0 а должен быть 1')
                w = w + e
                
            else:
                print('вычитаем из', w,' e - ',e , 'Predict == 1 а должен быть 0')
                w = w - e
                
        
print('final answer', w)

шаг 1
e = [ 1.   1.   0.3]
0 - Prdict(e) = = 1 - Target(e)
прибавляем к [[0 0 0]] ,e [ 1.   1.   0.3] Predict == 0 а должен быть 1
шаг 2
e = [ 1.   0.4  0.5]
1 - Prdict(e) = = 1 - Target(e)
шаг 3
e = [ 1.   0.7  0.8]
1 - Prdict(e) = = 0 - Target(e)
вычитаем из [[ 1.   1.   0.3]]  e -  [ 1.   0.7  0.8] Predict == 1 а должен быть 0
шаг 4
e = [ 1.   1.   0.3]
1 - Prdict(e) = = 1 - Target(e)
шаг 5
e = [ 1.   0.4  0.5]
0 - Prdict(e) = = 1 - Target(e)
прибавляем к [[ 0.   0.3 -0.5]] ,e [ 1.   0.4  0.5] Predict == 0 а должен быть 1
шаг 6
e = [ 1.   0.7  0.8]
1 - Prdict(e) = = 0 - Target(e)
вычитаем из [[ 1.   0.7  0. ]]  e -  [ 1.   0.7  0.8] Predict == 1 а должен быть 0
шаг 7
e = [ 1.   1.   0.3]
0 - Prdict(e) = = 1 - Target(e)
прибавляем к [[  0.00000000e+00   1.11022302e-16  -8.00000000e-01]] ,e [ 1.   1.   0.3] Predict == 0 а должен быть 1
шаг 8
e = [ 1.   0.4  0.5]
1 - Prdict(e) = = 1 - Target(e)
шаг 9
e = [ 1.   0.7  0.8]
1 - Prdict(e) = = 0 - Target(e)
вычитаем из [[ 1.   1.  -0.5]]  e

In [68]:
a = [1, 1, 0.3]
b = [1,0.4,0.5]
c = [1,0.7,0.8]

In [66]:
sw1 = [1, 1, 0.3]

In [69]:
sw2 = b[0]*sw1[0] + b[1]*sw1[1]+ b[2]*sw1[2]

In [77]:
sw2

1.5499999999999998

In [86]:
sw2s = [1-1, 1-0.4,0.3-0.5]

In [87]:
sw2s

[0, 0.6, -0.2]

In [82]:
sw3 = c[0]*sw2s[0] + c[1]*sw2s[1]+ c[2]*sw2s[2]

In [83]:
sw3

3.62

In [84]:
sw3s = [2-1, 1.4-0.7,0.8-0.8]

In [85]:
sw3s

[1, 0.7, 0.0]